import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import EmojiParticle from '../components/emoji-particles';
import { GeistSans } from 'geist/font/sans';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className={inter.className}>
        <EmojiParticle>{children}</EmojiParticle>
      </body>
    </html>
  );
}
